version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discipulo
    ports:
      - '5001:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/startup/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/startup/matchingData.sql:/docker-entrypoint-initdb.d/matchingData.sql
      - ./database/startup/interestTypes.sql:/docker-entrypoint-initdb.d/interestTypes.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
  server:
    build:
      context: ./server/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './server/:/src'
volumes:
  db:
    driver: local
